// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj1aN_9xY66fvfgclqcXUUmLME3ZwYKfE',
    appId: '1:777208492582:android:448e40f83ba3fca9222ce7',
    messagingSenderId: '777208492582',
    projectId: 'fir-flutter-codelab-89780',
    storageBucket: 'fir-flutter-codelab-89780.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjuNu4hEKjRT2CVUO9cpD7AKwBx4HdRgE',
    appId: '1:777208492582:ios:f49a926e31a01fc5222ce7',
    messagingSenderId: '777208492582',
    projectId: 'fir-flutter-codelab-89780',
    storageBucket: 'fir-flutter-codelab-89780.appspot.com',
    iosClientId: '777208492582-3rgnf2mq0tfmsclpf97qcnjceq4f0eao.apps.googleusercontent.com',
    iosBundleId: 'com.example.myImage',
  );
}
